# -*- coding: utf-8 -*-
"""Amazon_Reviews_Sentiment_Analysis_Using_ML_and_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSVb0gkqZknN8CdTXQg-CrnOj153SiHv
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
csv_file = "Reviews.csv"
df = pd.read_csv(csv_file, engine='python', on_bad_lines='skip')

# Binary sentiment conversion
df = df[df['Score'] != 3]  # drop neutral reviews
df['sentiment'] = df['Score'].apply(lambda x: 1 if x > 3 else 0)

# Drop rows where 'Text' is null to prevent AttributeError in TfidfVectorizer
df.dropna(subset=['Text'], inplace=True)

# Features and labels
X = df['Text']
y = df['sentiment']

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1,2))
X_vec = vectorizer.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_vec, y, test_size=0.2, random_state=42)

# Train Logistic Regression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Accuracy
accuracy = accuracy_score(y_test, model.predict(X_test))
print(f'Accuracy: {accuracy*100:.2f}%')

# Visualization 1: Sentiment Distribution
sns.countplot(x='sentiment', data=df)
plt.title("Sentiment Distribution (Positive vs Negative)")
plt.xlabel("Sentiment (0 = Negative, 1 = Positive)")
plt.ylabel("Count")
plt.show()

# -----------------------------
# Visualization 2: Confusion Matrix
y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Negative','Positive'],
            yticklabels=['Negative','Positive'])
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()